### ISSUE TITLE
I don't feel like I gained anything from that session. It was bewildering.

### ISSUE THREAD

**Issue by jrd656** [WebAhead/master-reference#6]
There are a few guys on the cohort who really did well on this and a few of us who didn't. I tried this for a good 70-80 minutes with help from the other students who had managed to complete it. I just couldn't get to grips with it at all - even with people showing me how they got to their answers. 

A couple of us were trying to approach the challenges based on what we've learned in the previous days, but we found the questions in this exercise didn't match up to the previous content. I felt that I couldn't/didn't get the benefit from the challenge.

Suggestions to improve would be to provide a hints section for each question, as they do on the hints in FreeCodeCamp. The first hint would ideally include an example of what the question is inputting (ie, an example object; html element; array), and the expected output. I often found that I wasn't even sure what the questions wanted, after several readings.

Further hints would ideally direct us (those of us who were equally as clueless as me) towards the final code, similarly to the hints in FreeCodeCamp. To be honest, if I'd just been given the answers and had a couple of hours to reverse-engineer them and learn the surrounding concepts, I'd have learned a lot more today than I did.

I appreciate this is largely down to my lack of understanding/learning styles, but since I'm not alone on this one I think future students would benefit from a bit of an overhaul on how this one is provided to students.

Sorry if this sounds overly negative. I'd just like to make sure other students don't end up feeling as deflated as me and that their time could have been better spent.

https://github.com/WebAhead/master-reference/edit/master/coursebook/week-2/dom-manipulation-ws.md

**Comment by Karyum** [comment]
just for clarification (since this is the entire curriculum repository) you're talking about the dom-manipulation-ws, correct?

**Comment by jrd656** [comment]
That's correct, yeah. Sorry - forgot to link to the section.

I've tried going back and doing it again this morning. I can't even get question 1 to do anything. The function isn't responding at all - the below image shows what's happening:

![image](https://user-images.githubusercontent.com/51966598/76928433-24f6a000-68ea-11ea-8e98-3f9dfe54a91d.png)

**Comment by Karyum** [comment]
ohhh yeah that's probably me, cause i was updating the workshop and checking some stuff, haven't finished. and i commented out line 195 - 197 in `tests.js` which runs the first 3 functions.
